apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: red-spark-team
  namespace: red-spark-team
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
    - host: red-spark-team.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80